version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.1"
    restart: always
    ports:
      - 27017:27017